"""Add enum management tables

Revision ID: 388c4c7e11ca
Revises: 219bd60709b9
Create Date: 2025-09-10 12:08:03.697351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388c4c7e11ca'
down_revision = '219bd60709b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###