"""verify_schema_sync

Revision ID: 4262638bedd3
Revises: 0ca237308aad
Create Date: 2025-10-06 20:09:45.284821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4262638bedd3'
down_revision = '0ca237308aad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###