"""add_selfies_table_for_flutter_capture

Revision ID: c54dc9b06c0a
Revises: 20250826_add_performance_indexes
Create Date: 2025-08-28 21:18:24.605092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54dc9b06c0a'
down_revision = '20250826_add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create selfies table for Flutter selfie capture workflow
    op.create_table('selfies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('application_id', sa.UUID(), nullable=False),
        sa.Column('file_id', sa.UUID(), nullable=False),
        sa.Column('selfie_type', sa.String(length=50), nullable=False),
        sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('captured_by_user_id', sa.UUID(), nullable=False),
        sa.Column('customer_id_number', sa.String(length=50), nullable=True),
        sa.Column('customer_name', sa.String(length=255), nullable=True),
        sa.Column('location_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('location_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('location_address', sa.Text(), nullable=True),
        sa.Column('face_detection_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('image_quality_score', sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('is_validated', sa.Boolean(), nullable=True),
        sa.Column('validated_by', sa.UUID(), nullable=True),
        sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('validation_notes', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['application_id'], ['customer_applications.id'], ),
        sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # Create indexes for better performance
    op.create_index('idx_selfies_application_id', 'selfies', ['application_id'])
    op.create_index('idx_selfies_captured_by_user_id', 'selfies', ['captured_by_user_id'])
    op.create_index('idx_selfies_selfie_type', 'selfies', ['selfie_type'])
    op.create_index('idx_selfies_status', 'selfies', ['status'])
    op.create_index('idx_selfies_captured_at', 'selfies', ['captured_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('idx_selfies_captured_at', table_name='selfies')
    op.drop_index('idx_selfies_status', table_name='selfies')
    op.drop_index('idx_selfies_selfie_type', table_name='selfies')
    op.drop_index('idx_selfies_captured_by_user_id', table_name='selfies')
    op.drop_index('idx_selfies_application_id', table_name='selfies')
    # Drop selfies table
    op.drop_table('selfies')
    # ### end Alembic commands ###