"""add_notification_table

Revision ID: cc3f3f59ab5b
Revises: 4262638bedd3
Create Date: 2025-10-07 08:27:11.988099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3f3f59ab5b'
down_revision = '4262638bedd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###