[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app.main:app --host=0.0.0.0 --port=8080"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3