# This pubspec defines the mobile library module
name: mobile
description: Shared mobile library for LC Workflow Flutter app
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  get: ^4.6.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  http_parser: ^4.0.2
  mime: ^1.0.5

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true