[build]
builder = "DOCKERFILE"
dockerfilePath = "/le-backend/Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8090 --proxy-headers --forwarded-allow-ips='*'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Environment variables for Railway deployment
[env]
# Basic configuration
ENVIRONMENT = "production"
LOG_LEVEL = "info"
DEBUG = "false"

# Railway will provide these automatically, but we can set defaults
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

# CORS - Railway will inject the correct frontend URL
CORS_ORIGINS = "${{FRONTEND_URL}}"

# Production optimizations
UVICORN_WORKERS = "1"
UVICORN_RELOAD = "false"
MAX_WORKERS = "4"

# Build configuration
[build.env]
PYTHON_VERSION = "3.11"
DOCKER_BUILDKIT = "1"