[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m app.main"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables for Railway deployment
[env]
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
# Allow the frontend origin for CORS (comma-separated list if multiple)
CORS_ORIGINS = "https://frontend-production-c749.up.railway.app"

# Build configuration
[build.env]
PYTHON_VERSION = "3.11"