[build]
builder = "dockerfile"
buildContext = "."
# Use relative path to Dockerfile inside this service directory
# Railway resolves from the service root; remove leading slash
dockerfilePath = "/lc-workflow-frontend/Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_API_URL = "https://backend-production-478f.up.railway.app"
NEXT_PUBLIC_WS_URL = "wss://backend-production-478f.up.railway.app"

# Ensure build-time args are passed to Docker so Next.js inlines them
[build.args]
NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"
NEXT_PUBLIC_WS_URL = "${NEXT_PUBLIC_WS_URL}"