[build]
builder = "dockerfile"
buildContext = "."
dockerfilePath = "/lc-workflow-frontend/Dockerfile"

# Build optimizations
[build.cache]
# Enable build caching for faster deployments
enable = true

# Build arguments - these will be populated from Railway environment variables
[build.args]
NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"
NEXT_PUBLIC_WS_URL = "${NEXT_PUBLIC_WS_URL}"
NEXT_PUBLIC_FORCE_HTTPS = "${NEXT_PUBLIC_FORCE_HTTPS:-true}"
NODE_ENV = "production"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Performance optimizations
[deploy.performance]
# Enable automatic performance monitoring
enable = true

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"

# Production optimizations
[env.production]
NODE_OPTIONS = "--max-old-space-size=4096 --optimize-for-size --max-semi-space-size=128"


