[build]
builder = "dockerfile"
buildContext = "."
dockerfilePath = "/lc-workflow-frontend/Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"

# Build arguments - these will be populated from Railway environment variables
[build.args]
NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"
NEXT_PUBLIC_WS_URL = "${NEXT_PUBLIC_WS_URL}"
NEXT_PUBLIC_FORCE_HTTPS = "${NEXT_PUBLIC_FORCE_HTTPS:-true}"