"""Add settings table

Revision ID: 44a7ba5fc5a3
Revises: dd726b2004d3
Create Date: 2025-08-01 09:30:29.706444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a7ba5fc5a3'
down_revision = 'dd726b2004d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###