"""Add frontend compatibility fields to customer applications

Revision ID: ce3939ec2771
Revises: 20250809_add_account_id
Create Date: 2025-08-13 16:40:30.915736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3939ec2771'
down_revision = '20250809_add_account_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_applications', sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('customer_applications', sa.Column('loan_status', sa.String(length=20), nullable=True))
    op.add_column('customer_applications', sa.Column('loan_purpose', sa.String(length=255), nullable=True))
    op.add_column('customer_applications', sa.Column('loan_start_date', sa.Date(), nullable=True))
    op.add_column('customer_applications', sa.Column('loan_end_date', sa.Date(), nullable=True))
    op.add_column('customer_applications', sa.Column('profile_image', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('borrower_nid_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('borrower_home_or_land_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('borrower_business_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('guarantor_nid_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('guarantor_home_or_land_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('guarantor_business_photo_path', sa.Text(), nullable=True))
    op.add_column('customer_applications', sa.Column('profile_photo_path', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_customer_applications_account_id'), table_name='customer_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_applications_account_id'), 'customer_applications', ['account_id'], unique=False)
    op.drop_column('customer_applications', 'profile_photo_path')
    op.drop_column('customer_applications', 'guarantor_business_photo_path')
    op.drop_column('customer_applications', 'guarantor_home_or_land_photo_path')
    op.drop_column('customer_applications', 'guarantor_nid_photo_path')
    op.drop_column('customer_applications', 'borrower_business_photo_path')
    op.drop_column('customer_applications', 'borrower_home_or_land_photo_path')
    op.drop_column('customer_applications', 'borrower_nid_photo_path')
    op.drop_column('customer_applications', 'profile_image')
    op.drop_column('customer_applications', 'loan_end_date')
    op.drop_column('customer_applications', 'loan_start_date')
    op.drop_column('customer_applications', 'loan_purpose')
    op.drop_column('customer_applications', 'loan_status')
    op.drop_column('customer_applications', 'loan_amount')
    # ### end Alembic commands ###