name: mobile_example
description: Example app for the shared mobile package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  mobile:
    path: ../

flutter:
  uses-material-design: true